{% set version = "0.1.6" %}

package:
  name: pyhat
  version: {{ version }}

source:
  git_url: https://github.com/USGS-Astrogeology/PyHAT
  git_rev: master

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  skip: True  # [not py3k]

requirements:
  build:
    - python x.x
    - numpy>=1.18
    - pandas
    - scipy
    - scikit-learn
    - multipledispatch
    - yaml
    - pvl
    - plio
    - matplotlib
    - pywavelets
  run:
    - python x.x
    - numpy>=1.18
    - pandas
    - scipy
    - scikit-learn
    - multipledispatch
    - yaml
    - pvl
    - plio
    - matplotlib
    - pywavelets

test:
  imports:
    - libpyhat

about:
  home: https://github.com/USGS-Astrogeology/PyHAT
  license: Unlicense
